server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'admin'
    hikari:
      catalog: 'public'
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: 'public'
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: 'classpath:db1/changelog/db.changelog-master.xml'
    default-schema: 'public'